language: node_js
node_js:
- '10'

script: npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    repo: tnguyen14/tnguyen14.github.io
    target-branch: master
    fqdn: tridnguyen.com
    local_dir: dist
    keep-history: true
    on:
      branch: master
