name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout gh-pages repo
        uses: actions/checkout@v2
        with:
          repository: tnguyen14/tnguyen14.github.io
          path: dist

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        # subtree instructions from https://gist.github.com/tduarte/eac064b4778711b116bb827f8c9bef7b
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email "deploy@tridnguyen.com"
          cd dist
          git add -f .
          git commit --no-verify -m "Update from commit tnguyen14/tridnguyen.com@$GITHUB_SHA"
          git push -f origin master:master

